import type { Movie, Source, TerritorySplit } from "./types";
import { round2 } from "./consensus";
import { addDays } from "./format";

export const SOURCES: Source[] = [
  {
    id: "sacnilk",
    name: "Sacnilk",
    homepage: "https://www.sacnilk.com/box-office-collections",
    kind: "trade",
    weight: 1,
    notes: "Daily all-India tracker. Primary live reference for net collections and shows.",
  },
  {
    id: "koimoi",
    name: "Koimoi",
    homepage: "https://www.koimoi.com/box-office/",
    kind: "trade",
    weight: 0.92,
    notes: "Trade desk with day-wise India net, gross and worldwide.",
  },
  {
    id: "hungama",
    name: "Bollywood Hungama",
    homepage: "https://www.bollywoodhungama.com/box-office-collections/",
    kind: "trade",
    weight: 0.88,
    notes: "Long-running Hindi trade tables. Often narrower (Hindi-weighted) than pan-India trackers.",
  },
  {
    id: "boi",
    name: "Box Office India",
    homepage: "https://www.boxofficeindia.com/",
    kind: "trade",
    weight: 0.9,
    notes: "Classic trade weekly. Slower, conservative nett. Does not cover all South films equally.",
  },
  {
    id: "pinkvilla",
    name: "Pinkvilla",
    homepage: "https://www.pinkvilla.com/entertainment/box-office",
    kind: "newsroom",
    weight: 0.7,
    notes: "Newsroom estimates, usually India gross, citing trade.",
  },
  {
    id: "express",
    name: "Indian Express",
    homepage: "https://indianexpress.com/section/entertainment/bollywood/box-office-collection/",
    kind: "newsroom",
    weight: 0.68,
    notes: "Reported figures attributed to Sacnilk and other trackers.",
  },
  {
    id: "etimes",
    name: "ETimes",
    homepage: "https://timesofindia.indiatimes.com/entertainment",
    kind: "newsroom",
    weight: 0.65,
    notes: "Times of India entertainment desk, language-wise splits on big openings.",
  },
  {
    id: "wikipedia",
    name: "Wikipedia compiled",
    homepage: "https://en.wikipedia.org/wiki/List_of_Indian_films_of_2026",
    kind: "compiler",
    weight: 0.45,
    notes: "Secondary compilation of published worldwide grosses. Lags live trade.",
  },
  {
    id: "producer",
    name: "Producer statement",
    homepage: "",
    kind: "compiler",
    weight: 0.35,
    notes: "Studio / producer claimed gross. Logged for spread, never used as sole consensus. No canonical URL.",
  },
];

export const MOVIES: Movie[] = [
  {
    id: "toxic",
    slug: "toxic",
    title: "Toxic",
    language: "Kannada",
    industry: "Sandalwood / Pan-India",
    director: "Geetu Mohandas",
    starring: "Yash, Kiara Advani, Nayanthara, Huma Qureshi, Tara Sutaria, Rukmini Vasanth",
    releaseDate: "2026-08-26",
    budgetCr: 500,
    runtimeMin: 235,
    synopsis:
      "A pan-India drama set in post-independence Goa. Dual-role Yash vehicle that opened like a mass film and is holding like a divided one.",
    posterKey: "toxic",
    status: "playing",
    verdict: "Pending",
  },
  {
    id: "awarapan-2",
    slug: "awarapan-2",
    title: "Awarapan 2",
    language: "Hindi",
    industry: "Bollywood",
    director: "Nitin Kakkar",
    starring: "Emraan Hashmi",
    releaseDate: "2026-08-14",
    budgetCr: 45,
    runtimeMin: 148,
    synopsis:
      "Vishesh Films sequel. Quiet Independence-weekend build, then a genuine word-of-mouth climb into the 100-crore club.",
    posterKey: "awarapan-2",
    status: "playing",
    verdict: "Hit",
  },
  {
    id: "vishwanath-and-sons",
    slug: "vishwanath-and-sons",
    title: "Vishwanath And Sons",
    language: "Tamil",
    industry: "Kollywood",
    director: "Nandha Periyasamy",
    starring: "Suriya, Mamitha Baiju",
    releaseDate: "2026-08-14",
    budgetCr: 80,
    runtimeMin: 162,
    synopsis:
      "Suriya family drama with a slow theatrical burn. Producer gross and Sacnilk remain tens of crores apart — the year's clearest reporting gap.",
    posterKey: "vishwanath",
    status: "playing",
    verdict: "Hit",
  },
  {
    id: "irumudi",
    slug: "irumudi",
    title: "Irumudi",
    language: "Telugu",
    industry: "Tollywood",
    director: "Shiva Nirvana",
    starring: "Ravi Teja, Baby Nakshathra",
    releaseDate: "2026-08-21",
    budgetCr: 60,
    runtimeMin: 155,
    synopsis:
      "Ayyappa Deeksha road film that turned into Ravi Teja's cleanest family hold of the decade, led by Nizam.",
    posterKey: "irumudi",
    status: "playing",
    verdict: "Super Hit",
  },
  {
    id: "batwara-1947",
    slug: "batwara-1947",
    title: "Batwara 1947",
    language: "Hindi",
    industry: "Bollywood",
    director: "Anil Sharma",
    starring: "Gippy Grewal, Mahie Gill",
    releaseDate: "2026-08-14",
    budgetCr: 40,
    runtimeMin: 141,
    synopsis: "Partition drama that found a North circuit but not a national breakout.",
    posterKey: "batwara",
    status: "playing",
    verdict: "Average",
  },
  {
    id: "hi",
    slug: "hi",
    title: "Hi",
    language: "Tamil",
    industry: "Kollywood",
    director: "Gokul",
    starring: "Nayanthara, Kavin",
    releaseDate: "2026-08-28",
    budgetCr: 25,
    runtimeMin: 138,
    synopsis: "Small-to-mid Tamil release climbing on Sunday occupancy rather than a Friday blast.",
    posterKey: "hi",
    status: "playing",
    verdict: "Pending",
  },
  {
    id: "insidious-further",
    slug: "insidious-out-of-the-further",
    title: "Insidious: Out of The Further",
    language: "English",
    industry: "Hollywood",
    director: "Patrick Wilson",
    starring: "Ty Simpkins, Patrick Wilson",
    releaseDate: "2026-08-21",
    budgetCr: null,
    runtimeMin: 107,
    synopsis: "Horror holdover with a serviceable multiplex opening and a fast weekday fade.",
    posterKey: "insidious-further",
    status: "playing",
    verdict: "Pending",
  },
  {
    id: "paw-patrol-dino",
    slug: "paw-patrol-the-dino-movie",
    title: "PAW Patrol: The Dino Movie",
    language: "English",
    industry: "Hollywood",
    director: "Cal Brunker",
    starring: "Animated",
    releaseDate: "2026-08-21",
    budgetCr: null,
    runtimeMin: 90,
    synopsis: "Kids' matinee title. Modest India gross, weekend-weighted.",
    posterKey: "paw-patrol-dino",
    status: "playing",
    verdict: "Pending",
  },
  {
    id: "hanuman-ansh",
    slug: "hanuman-ansh",
    title: "Hanuman Ansh",
    language: "Hindi",
    industry: "Bollywood",
    director: "Charuvi Agrawal",
    starring: "Animated",
    releaseDate: "2026-08-07",
    budgetCr: 30,
    runtimeMin: 112,
    synopsis: "Devotional animation with a long thin tail rather than an opening.",
    posterKey: "hanuman-ansh",
    status: "late",
    verdict: "Flop",
  },
  {
    id: "sardar-2",
    slug: "sardar-2",
    title: "Sardar 2",
    language: "Tamil",
    industry: "Kollywood",
    director: "P. S. Mithran",
    starring: "Karthi",
    releaseDate: "2026-09-10",
    budgetCr: null,
    runtimeMin: null,
    synopsis: "Karthi's spy-action sequel opened in India on September 10, 2026.",
    posterKey: "sardar-2",
    status: "playing",
    verdict: "Pending",
  },
  {
    id: "haiwaan",
    slug: "haiwaan",
    title: "Haiwaan",
    language: "Hindi",
    industry: "Bollywood",
    director: "Priyadarshan",
    starring: "Akshay Kumar, Saif Ali Khan",
    releaseDate: "2026-09-11",
    budgetCr: null,
    runtimeMin: null,
    synopsis: "Priyadarshan's Hindi thriller released in India on September 11, 2026.",
    posterKey: "haiwaan",
    status: "playing",
    verdict: "Pending",
  },
  {
    id: "spider-man-bnd",
    slug: "spider-man-brand-new-day",
    title: "Spider-Man: Brand New Day",
    language: "English",
    industry: "Hollywood",
    director: "Destin Daniel Cretton",
    starring: "Tom Holland",
    releaseDate: "2026-07-30",
    budgetCr: null,
    runtimeMin: 132,
    synopsis: "The year's biggest Hollywood grosser in India. Still occupying premium screens in week five.",
    posterKey: "spider-man-bnd",
    status: "late",
    verdict: "All Time Blockbuster",
  },
  {
    id: "dhamaal-4",
    slug: "dhamaal-4",
    title: "Dhamaal 4",
    language: "Hindi",
    industry: "Bollywood",
    director: "Kapil Sharma",
    starring: "Arshad Warsi, Javed Jaffrey, Riteish Deshmukh",
    releaseDate: "2026-07-10",
    budgetCr: 80,
    runtimeMin: 144,
    synopsis: "Comedy franchise that paid for itself without becoming a cultural event.",
    posterKey: "dhamaal-4",
    status: "late",
    verdict: "Hit",
  },
  {
    id: "the-odyssey",
    slug: "the-odyssey",
    title: "The Odyssey",
    language: "English",
    industry: "Hollywood",
    director: "Christopher Nolan",
    starring: "Matt Damon, Tom Holland, Anne Hathaway",
    releaseDate: "2026-07-17",
    budgetCr: null,
    runtimeMin: 171,
    synopsis: "Prestige Hollywood hold. India is a premium-screen story, not a mass one.",
    posterKey: "the-odyssey",
    status: "late",
    verdict: "Pending",
  },
  {
    id: "dhurandhar",
    slug: "dhurandhar-the-revenge",
    title: "Dhurandhar: The Revenge",
    language: "Hindi",
    industry: "Bollywood",
    director: "Aditya Dhar",
    starring: "Ranveer Singh, Akshaye Khanna, R. Madhavan, Sanjay Dutt",
    releaseDate: "2026-03-19",
    budgetCr: 250,
    runtimeMin: 235,
    synopsis:
      "The film that bent 2026. Roughly a fifth of India's first-half box office sat in this one title.",
    posterKey: "dhurandhar",
    status: "closed",
    verdict: "All Time Blockbuster",
  },
  {
    id: "border-2",
    slug: "border-2",
    title: "Border 2",
    language: "Hindi",
    industry: "Bollywood",
    director: "Anoop Sathyan",
    starring: "Sunny Deol, Varun Dhawan, Diljit Dosanjh, Ahan Shetty",
    releaseDate: "2026-01-23",
    budgetCr: 150,
    runtimeMin: 200,
    synopsis: "Republic Day war film. Second-highest Indian grosser of the year, a long way behind Dhurandhar.",
    posterKey: "border-2",
    status: "closed",
    verdict: "Blockbuster",
  },
  {
    id: "peddi",
    slug: "peddi",
    title: "Peddi",
    language: "Telugu",
    industry: "Tollywood",
    director: "Buchireddy Mallidi",
    starring: "Ram Charan, Janhvi Kapoor",
    releaseDate: "2026-03-27",
    budgetCr: 200,
    runtimeMin: 168,
    synopsis: "Sports drama whose worldwide gross is still published as a range — ₹330 to ₹400 crore.",
    posterKey: "peddi",
    status: "closed",
    verdict: "Blockbuster",
  },
  {
    id: "jana-nayagan",
    slug: "jana-nayagan",
    title: "Jana Nayagan",
    language: "Tamil",
    industry: "Kollywood",
    director: "H. Vinoth",
    starring: "Vijay",
    releaseDate: "2026-01-10",
    budgetCr: 250,
    runtimeMin: 168,
    synopsis: "Vijay's theatrical farewell. Tight 320–325 crore band across newsrooms, now on ZEE5.",
    posterKey: "jana-nayagan",
    status: "closed",
    verdict: "Blockbuster",
  },
  {
    id: "karuppu",
    slug: "karuppu",
    title: "Karuppu",
    language: "Tamil",
    industry: "Kollywood",
    director: "R. Ajay Gnanamuthu",
    starring: "Suriya",
    releaseDate: "2026-04-10",
    budgetCr: 120,
    runtimeMin: 157,
    synopsis: "Suriya's mass register. Paired with Vishwanath And Sons, his most complete year.",
    posterKey: "karuppu",
    status: "closed",
    verdict: "Blockbuster",
  },
  {
    id: "msvpg",
    slug: "mana-shankara-vara-prasad-garu",
    title: "Mana Shankara Vara Prasad Garu",
    language: "Telugu",
    industry: "Tollywood",
    director: "Anil Ravipudi",
    starring: "Chiranjeevi",
    releaseDate: "2026-01-12",
    budgetCr: 150,
    runtimeMin: 161,
    synopsis: "Sankranti Megastar film. Solid 300-crore worldwide without dominating the year.",
    posterKey: "msvpg",
    status: "closed",
    verdict: "Hit",
  },
  {
    id: "bhooth-bangla",
    slug: "bhooth-bangla",
    title: "Bhooth Bangla",
    language: "Hindi",
    industry: "Bollywood",
    director: "Priyadarshan",
    starring: "Akshay Kumar, Taapsee Pannu",
    releaseDate: "2026-04-03",
    budgetCr: 130,
    runtimeMin: 149,
    synopsis: "Comedy-horror that landed as a paid-up performer rather than a runaway.",
    posterKey: "bhooth-bangla",
    status: "closed",
    verdict: "Average",
  },
  {
    id: "drishyam-3",
    slug: "drishyam-3",
    title: "Drishyam 3",
    language: "Malayalam",
    industry: "Mollywood",
    director: "Jeethu Joseph",
    starring: "Mohanlal",
    releaseDate: "2026-02-19",
    budgetCr: 70,
    runtimeMin: 165,
    synopsis: "The franchise still prints money in Malayalam and dubbed Hindi without needing a splash opening.",
    posterKey: "drishyam-3",
    status: "closed",
    verdict: "Blockbuster",
  },
  {
    id: "vaazha-ii",
    slug: "vaazha-ii",
    title: "Vaazha II: Biopic of a Billion Bros",
    language: "Malayalam",
    industry: "Mollywood",
    director: "Kannan Thamarakkulam",
    starring: "Basil Joseph",
    releaseDate: "2026-03-06",
    budgetCr: 20,
    runtimeMin: 142,
    synopsis: "Sequel that out-earned its scale. A Mollywood word-of-mouth case study.",
    posterKey: "vaazha-ii",
    status: "closed",
    verdict: "Blockbuster",
  },
  {
    id: "welcome-jungle",
    slug: "welcome-to-the-jungle",
    title: "Welcome To The Jungle",
    language: "Hindi",
    industry: "Bollywood",
    director: "Ahmed Khan",
    starring: "Akshay Kumar, Disha Patani",
    releaseDate: "2026-06-26",
    budgetCr: 100,
    runtimeMin: 146,
    synopsis: "Early-summer comedy that held a multiplex floor into July.",
    posterKey: "welcome-jungle",
    status: "closed",
    verdict: "Hit",
  },
  {
    id: "cocktail-2",
    slug: "cocktail-2",
    title: "Cocktail 2",
    language: "Hindi",
    industry: "Bollywood",
    director: "Homi Adajania",
    starring: "Saif Ali Khan, Deepika Padukone, Diana Penty",
    releaseDate: "2026-06-19",
    budgetCr: 90,
    runtimeMin: 139,
    synopsis: "Nostalgia sequel. Average verdict, adult multiplex.",
    posterKey: "cocktail-2",
    status: "closed",
    verdict: "Average",
  },
  {
    id: "alpha",
    slug: "alpha",
    title: "Alpha",
    language: "Hindi",
    industry: "Bollywood",
    director: "Shiv Rawail",
    starring: "Alia Bhatt, Sharvari",
    releaseDate: "2026-07-03",
    budgetCr: 140,
    runtimeMin: 128,
    synopsis: "YRF spy-verse entry that opened and then fell off a cliff.",
    posterKey: "alpha",
    status: "closed",
    verdict: "Flop",
  },
];

export const SACNILK_PAGES: { movieId: string; slug: string }[] = [
  { movieId: "toxic", slug: "toxic_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "awarapan-2", slug: "awarapan_2_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "irumudi", slug: "irumudi_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "border-2", slug: "border_2_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "hi", slug: "hi_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "batwara-1947", slug: "batwara_1947_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "vishwanath-and-sons", slug: "vishwanath_and_sons_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "dhurandhar", slug: "dhurandhar_2_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "peddi", slug: "peddi_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "spider-man-bnd", slug: "spider_man_brand_new_day_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "dhamaal-4", slug: "dhamaal_4_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "karuppu", slug: "karuppu_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "welcome-jungle", slug: "welcome_to_the_jungle_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "hanuman-ansh", slug: "hanuman_ansh_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "sardar-2", slug: "sardar_2_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "haiwaan", slug: "haiwaan_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "the-odyssey", slug: "the_odyssey_2026_Box_Office_Collection_Day_Wise_Worldwide" },
  { movieId: "cocktail-2", slug: "cocktail_2_2026_Box_Office_Collection_Day_Wise_Worldwide" },
];

export const HUNGAMA_PAGES: { movieId: string; slug: string }[] = [
  { movieId: "toxic", slug: "toxic" },
  { movieId: "awarapan-2", slug: "awarapan-2" },
  { movieId: "border-2", slug: "border-2" },
  { movieId: "dhurandhar", slug: "dhurandhar-the-revenge" },
  { movieId: "dhamaal-4", slug: "dhamaal-4" },
  { movieId: "batwara-1947", slug: "batwara-1947" },
  { movieId: "welcome-jungle", slug: "welcome-to-the-jungle" },
  { movieId: "cocktail-2", slug: "cocktail-2" },
  { movieId: "alpha", slug: "alpha" },
  { movieId: "bhooth-bangla", slug: "bhooth-bangla" },
  { movieId: "peddi", slug: "peddi" },
  { movieId: "hanuman-ansh", slug: "hanuman-ansh" },
  { movieId: "spider-man-bnd", slug: "spider-man-brand-new-day" },
  { movieId: "the-odyssey", slug: "the-odyssey" },
  { movieId: "insidious-further", slug: "insidious-out-of-the-further" },
];

/** Koimoi day-wise pages. Often Cloudflare-blocked; publisher keeps seed rows when live pull fails. */
export const KOIMOI_PAGES: { movieId: string; slug: string }[] = [
  { movieId: "toxic", slug: "toxic-day-wise-box-office-collection" },
  { movieId: "awarapan-2", slug: "awarapan-2-day-wise-box-office-collection" },
  { movieId: "dhamaal-4", slug: "dhamaal-4-day-wise-box-office-collection" },
  { movieId: "border-2", slug: "border-2-day-wise-box-office-collection" },
  { movieId: "dhurandhar", slug: "dhurandhar-the-revenge-day-wise-box-office-collection" },
  { movieId: "spider-man-bnd", slug: "spider-man-brand-new-day-day-wise-box-office-collection" },
  { movieId: "batwara-1947", slug: "batwara-1947-day-wise-box-office-collection" },
  { movieId: "hanuman-ansh", slug: "hanuman-ansh-day-wise-box-office-collection" },
];


export type Point = {
  day: number;
  indiaNet: number;
  indiaGross?: number;
  overseas?: number;
  worldwide?: number;
  screens?: number;
  occupancy?: number;
  note?: string;
};

export type Series = {
  movieId: string;
  sourceId: string;
  mode: "daily" | "lifetime";
  points: Point[];
};

const gross = (net: number) => round2(net * 1.18);

function fillDaily(movieId: string, sourceId: string, points: Point[]): Series {
  return {
    movieId,
    sourceId,
    mode: "daily",
    points: points.map((p) => ({
      ...p,
      indiaGross: p.indiaGross ?? gross(p.indiaNet),
      overseas: p.overseas ?? round2(p.indiaNet * 0.12),
      worldwide: p.worldwide ?? round2((p.indiaGross ?? gross(p.indiaNet)) + (p.overseas ?? round2(p.indiaNet * 0.12))),
    })),
  };
}

function lifetime(
  movieId: string,
  sourceId: string,
  day: number,
  nums: { indiaNet?: number; indiaGross?: number; overseas?: number; worldwide: number },
  note: string,
): Series {
  return {
    movieId,
    sourceId,
    mode: "lifetime",
    points: [
      {
        day,
        indiaNet: nums.indiaNet ?? 0,
        indiaGross: nums.indiaGross ?? 0,
        overseas: nums.overseas ?? 0,
        worldwide: nums.worldwide,
        note,
      },
    ],
  };
}

export const SERIES: Series[] = [
  fillDaily("toxic", "sacnilk", [
    { day: 1, indiaNet: 101.1, indiaGross: 119.3, overseas: 20.0, worldwide: 139.3, screens: 24579, occupancy: 71.4 },
    { day: 2, indiaNet: 37.65, indiaGross: 44.43, overseas: 3.5, worldwide: 47.93, screens: 22629, occupancy: 38.2 },
    { day: 3, indiaNet: 27.2, indiaGross: 32.1, overseas: 3.5, worldwide: 35.6, screens: 18495, occupancy: 28.6 },
    { day: 4, indiaNet: 24.5, indiaGross: 28.91, overseas: 3.6, worldwide: 32.51, screens: 16643, occupancy: 26.1 },
    { day: 5, indiaNet: 18.4, indiaGross: 21.71, overseas: 2.8, worldwide: 24.51, screens: 15820, occupancy: 22.4 },
    { day: 6, indiaNet: 6.85, indiaGross: 8.08, overseas: 0.9, worldwide: 8.98, screens: 14210, occupancy: 11.8 },
  ]),
  fillDaily("toxic", "koimoi", [
    { day: 1, indiaNet: 101.1, indiaGross: 119.3, overseas: 20.0, worldwide: 139.3 },
    { day: 2, indiaNet: 37.65, indiaGross: 44.43, overseas: 3.5, worldwide: 47.93 },
    { day: 3, indiaNet: 27.2, indiaGross: 32.1, overseas: 3.5, worldwide: 35.6 },
    { day: 4, indiaNet: 24.5, indiaGross: 28.91, overseas: 3.6, worldwide: 32.51 },
    { day: 5, indiaNet: 17.9, indiaGross: 21.12, overseas: 2.6, worldwide: 23.72 },
    { day: 6, indiaNet: 6.4, indiaGross: 7.55, overseas: 0.8, worldwide: 8.35 },
  ]),
  fillDaily("toxic", "hungama", [
    { day: 1, indiaNet: 50.31, indiaGross: 59.37, overseas: 20.0, worldwide: 79.37, screens: 24481, occupancy: 55.7, note: "Hungama Hindi-weighted nett; pan-India trackers are roughly 2× on Day 1." },
    { day: 2, indiaNet: 21.75, indiaGross: 25.67, occupancy: 23.9, screens: 22229 },
    { day: 3, indiaNet: 17.4, indiaGross: 20.53, occupancy: 21.5, screens: 18495 },
    { day: 4, indiaNet: 13.9, indiaGross: 16.4, occupancy: 21.1, screens: 16643 },
    { day: 5, indiaNet: 12.85, indiaGross: 15.16, occupancy: 19.4 },
    { day: 6, indiaNet: 4.2, indiaGross: 4.96, occupancy: 9.8 },
  ]),
  fillDaily("toxic", "pinkvilla", [
    { day: 1, indiaNet: 94.7, indiaGross: 111.75, overseas: 20, worldwide: 131.75, note: "Pinkvilla published India gross; net reverse-estimated." },
    { day: 2, indiaNet: 32.63, indiaGross: 38.5 },
    { day: 3, indiaNet: 23.52, indiaGross: 27.75 },
    { day: 4, indiaNet: 20.1, indiaGross: 23.72 },
    { day: 5, indiaNet: 15.6, indiaGross: 18.41 },
    { day: 6, indiaNet: 5.9, indiaGross: 6.96 },
  ]),
  fillDaily("toxic", "express", [
    { day: 1, indiaNet: 101.1, indiaGross: 120.75, overseas: 20, worldwide: 140.75, note: "Indian Express citing Sacnilk." },
    { day: 2, indiaNet: 36.4, indiaGross: 43.8, overseas: 10.0, worldwide: 53.8, note: "Day-2 live updates; overseas reported as two-day cume in some copies." },
    { day: 3, indiaNet: 27.2, indiaGross: 32.1 },
  ]),
  fillDaily("toxic", "etimes", [
    { day: 1, indiaNet: 101.1, indiaGross: 120.75, overseas: 20, worldwide: 140.75, note: "Language split published: Hindi 55, Kannada 23.3, Telugu 16, Tamil 5.5, Malayalam 1.3." },
    { day: 2, indiaNet: 36.4, indiaGross: 43.8 },
  ]),
  lifetime("toxic", "wikipedia", 5, { worldwide: 254.75, indiaGross: 224.0, indiaNet: 190.0, overseas: 30.75 }, "Wikipedia worldwide as compiled 31 Aug. Trails live trade."),

  fillDaily("awarapan-2", "koimoi", [
    { day: 1, indiaNet: 23.4, indiaGross: 27.61, overseas: 5.0, worldwide: 32.61 },
    { day: 2, indiaNet: 34.09, indiaGross: 40.23, overseas: 8.0, worldwide: 48.23 },
    { day: 3, indiaNet: 26.82, indiaGross: 31.65, overseas: 6.31, worldwide: 37.96 },
    { day: 4, indiaNet: 10.06, indiaGross: 11.87, overseas: 2.5, worldwide: 14.37 },
    { day: 5, indiaNet: 8.2, indiaGross: 9.68 },
    { day: 6, indiaNet: 7.1, indiaGross: 8.38 },
    { day: 7, indiaNet: 6.4, indiaGross: 7.55 },
    { day: 8, indiaNet: 5.15, indiaGross: 6.08 },
    { day: 9, indiaNet: 7.85, indiaGross: 9.26 },
    { day: 10, indiaNet: 8.4, indiaGross: 9.91 },
    { day: 11, indiaNet: 2.75, indiaGross: 3.25 },
    { day: 12, indiaNet: 2.4, indiaGross: 2.83 },
    { day: 13, indiaNet: 2.15, indiaGross: 2.54 },
    { day: 14, indiaNet: 1.95, indiaGross: 2.3 },
    { day: 15, indiaNet: 2.55, indiaGross: 3.01 },
    { day: 16, indiaNet: 2.1, indiaGross: 2.48 },
    { day: 17, indiaNet: 1.35, indiaGross: 1.59 },
    { day: 18, indiaNet: 0.95, indiaGross: 1.12 },
  ]),
  fillDaily("awarapan-2", "hungama", [
    { day: 1, indiaNet: 21.89, indiaGross: 25.83, overseas: 5.11, worldwide: 30.94 },
    { day: 2, indiaNet: 32.4, indiaGross: 38.23 },
    { day: 3, indiaNet: 27.21, indiaGross: 32.11 },
    { day: 4, indiaNet: 9.8, indiaGross: 11.56 },
    { day: 5, indiaNet: 7.9, indiaGross: 9.32 },
    { day: 6, indiaNet: 6.7, indiaGross: 7.91 },
    { day: 7, indiaNet: 5.26, indiaGross: 6.21 },
    { day: 8, indiaNet: 4.8, indiaGross: 5.66 },
    { day: 9, indiaNet: 7.2, indiaGross: 8.5 },
    { day: 10, indiaNet: 7.6, indiaGross: 8.97 },
    { day: 11, indiaNet: 2.4, indiaGross: 2.83 },
    { day: 12, indiaNet: 2.1, indiaGross: 2.48 },
    { day: 13, indiaNet: 1.9, indiaGross: 2.24 },
    { day: 14, indiaNet: 1.7, indiaGross: 2.01 },
    { day: 15, indiaNet: 2.2, indiaGross: 2.6 },
    { day: 16, indiaNet: 1.85, indiaGross: 2.18 },
    { day: 17, indiaNet: 1.15, indiaGross: 1.36 },
    { day: 18, indiaNet: 0.82, indiaGross: 0.97 },
  ]),
  fillDaily("awarapan-2", "sacnilk", [
    { day: 1, indiaNet: 23.1, indiaGross: 27.26 },
    { day: 2, indiaNet: 33.8, indiaGross: 39.88 },
    { day: 3, indiaNet: 26.4, indiaGross: 31.15 },
    { day: 4, indiaNet: 10.2, indiaGross: 12.04 },
    { day: 5, indiaNet: 8.05, indiaGross: 9.5 },
    { day: 6, indiaNet: 7.0, indiaGross: 8.26 },
    { day: 7, indiaNet: 6.2, indiaGross: 7.32 },
    { day: 8, indiaNet: 5.0, indiaGross: 5.9 },
    { day: 9, indiaNet: 7.6, indiaGross: 8.97 },
    { day: 10, indiaNet: 8.15, indiaGross: 9.62 },
    { day: 11, indiaNet: 2.75, indiaGross: 3.25 },
    { day: 12, indiaNet: 2.35, indiaGross: 2.77 },
    { day: 13, indiaNet: 2.1, indiaGross: 2.48 },
    { day: 14, indiaNet: 1.9, indiaGross: 2.24 },
    { day: 15, indiaNet: 2.45, indiaGross: 2.89 },
    { day: 16, indiaNet: 2.05, indiaGross: 2.42 },
    { day: 17, indiaNet: 1.28, indiaGross: 1.51 },
    { day: 18, indiaNet: 0.9, indiaGross: 1.06 },
  ]),
  lifetime("awarapan-2", "wikipedia", 18, { worldwide: 199.54, indiaGross: 170.9, indiaNet: 144.8, overseas: 28.64 }, "Wikipedia lifetime gross."),

  fillDaily("vishwanath-and-sons", "sacnilk", [
    { day: 1, indiaNet: 18.4, indiaGross: 21.71, overseas: 13.4, worldwide: 35.11 },
    { day: 2, indiaNet: 16.1, indiaGross: 19.0, overseas: 8.2 },
    { day: 3, indiaNet: 14.8, indiaGross: 17.46, overseas: 9.1 },
    { day: 4, indiaNet: 6.2, indiaGross: 7.32, overseas: 3.4 },
    { day: 5, indiaNet: 5.4, indiaGross: 6.37 },
    { day: 6, indiaNet: 5.05, indiaGross: 5.96 },
    { day: 7, indiaNet: 4.7, indiaGross: 5.55 },
    { day: 8, indiaNet: 4.15, indiaGross: 4.9 },
    { day: 9, indiaNet: 6.35, indiaGross: 7.49 },
    { day: 10, indiaNet: 6.9, indiaGross: 8.14, overseas: 4.2, note: "Sacnilk ~₹173.9 Cr WW vs producer ₹200 Cr on Day 10." },
    { day: 11, indiaNet: 3.1, indiaGross: 3.66 },
    { day: 12, indiaNet: 2.7, indiaGross: 3.19 },
    { day: 13, indiaNet: 2.35, indiaGross: 2.77 },
    { day: 14, indiaNet: 1.3, indiaGross: 1.53 },
    { day: 15, indiaNet: 1.7, indiaGross: 2.01 },
    { day: 16, indiaNet: 2.61, indiaGross: 3.08, overseas: 1.1, note: "Sacnilk: India net cume ₹113.46 Cr; WW ₹193.34 Cr." },
    { day: 17, indiaNet: 2.55, indiaGross: 3.01, note: "ETimes: ₹2.55 Cr net, 1.9% dip from Saturday." },
    { day: 18, indiaNet: 1.05, indiaGross: 1.24 },
  ]),
  fillDaily("vishwanath-and-sons", "etimes", [
    { day: 16, indiaNet: 2.61, indiaGross: 3.08 },
    { day: 17, indiaNet: 2.55, indiaGross: 3.01 },
  ]),
  lifetime("vishwanath-and-sons", "producer", 17, { worldwide: 247, indiaGross: 170, indiaNet: 145, overseas: 77 }, "Studio claim ~₹247 Cr worldwide. Sacnilk is ~₹50 Cr lower."),
  lifetime("vishwanath-and-sons", "express", 4, { worldwide: 121.27, indiaGross: 78, indiaNet: 66, overseas: 43 }, "Indian Express Day-4 worldwide gross."),

  fillDaily("irumudi", "sacnilk", [
    { day: 1, indiaNet: 12.4, indiaGross: 14.63, overseas: 4.8 },
    { day: 2, indiaNet: 14.1, indiaGross: 16.64, overseas: 5.2 },
    { day: 3, indiaNet: 16.8, indiaGross: 19.82, overseas: 6.1 },
    { day: 4, indiaNet: 8.2, indiaGross: 9.68 },
    { day: 5, indiaNet: 7.4, indiaGross: 8.73 },
    { day: 6, indiaNet: 6.9, indiaGross: 8.14 },
    { day: 7, indiaNet: 6.2, indiaGross: 7.32 },
    { day: 8, indiaNet: 9.4, indiaGross: 11.09 },
    { day: 9, indiaNet: 10.1, indiaGross: 11.92, note: "WW ~₹152.5 Cr by Day 9." },
    { day: 10, indiaNet: 8.6, indiaGross: 10.15, note: "Crossed ₹100 Cr share." },
    { day: 11, indiaNet: 3.4, indiaGross: 4.01 },
  ]),
  lifetime("irumudi", "producer", 10, { worldwide: 160, indiaGross: 125, indiaNet: 108, overseas: 35 }, "Producer-adjacent trade notes on the ₹150 Cr+ WW sprint."),

  fillDaily("batwara-1947", "hungama", [
    { day: 1, indiaNet: 5.52, indiaGross: 6.51 },
    { day: 2, indiaNet: 10.18, indiaGross: 12.01 },
    { day: 3, indiaNet: 9.75, indiaGross: 11.51 },
    { day: 4, indiaNet: 3.4, indiaGross: 4.01 },
    { day: 5, indiaNet: 2.2, indiaGross: 2.6 },
    { day: 6, indiaNet: 1.85, indiaGross: 2.18 },
    { day: 7, indiaNet: 1.41, indiaGross: 1.66 },
    { day: 8, indiaNet: 0.95, indiaGross: 1.12 },
    { day: 9, indiaNet: 1.15, indiaGross: 1.36 },
    { day: 10, indiaNet: 1.05, indiaGross: 1.24 },
    { day: 11, indiaNet: 0.42, indiaGross: 0.5 },
    { day: 12, indiaNet: 0.35, indiaGross: 0.41 },
    { day: 13, indiaNet: 0.28, indiaGross: 0.33 },
    { day: 14, indiaNet: 0.22, indiaGross: 0.26 },
    { day: 15, indiaNet: 0.31, indiaGross: 0.37 },
    { day: 16, indiaNet: 0.24, indiaGross: 0.28 },
    { day: 17, indiaNet: 0.18, indiaGross: 0.21 },
    { day: 18, indiaNet: 0.12, indiaGross: 0.14 },
  ]),

  fillDaily("hi", "sacnilk", [
    { day: 1, indiaNet: 1.25, indiaGross: 1.48, screens: 786, note: "Sacnilk Day 1 across 786 shows." },
    { day: 2, indiaNet: 1.55, indiaGross: 1.83 },
    { day: 3, indiaNet: 2.43, indiaGross: 2.87, occupancy: 47, note: "ETimes: India net cume ₹5.23 Cr; Sunday occupancy 47%." },
    { day: 4, indiaNet: 0.72, indiaGross: 0.85 },
  ]),
  fillDaily("hi", "etimes", [
    { day: 3, indiaNet: 2.43, indiaGross: 2.87, occupancy: 47, note: "Cume ₹5.23 Cr India net through Sunday." },
  ]),

  fillDaily("insidious-further", "hungama", [
    { day: 1, indiaNet: 2.46, indiaGross: 2.9 },
    { day: 2, indiaNet: 4.12, indiaGross: 4.86 },
    { day: 3, indiaNet: 4.06, indiaGross: 4.79 },
    { day: 4, indiaNet: 1.55, indiaGross: 1.83 },
    { day: 5, indiaNet: 1.18, indiaGross: 1.39 },
    { day: 6, indiaNet: 0.96, indiaGross: 1.13 },
    { day: 7, indiaNet: 0.7, indiaGross: 0.83 },
    { day: 8, indiaNet: 0.42, indiaGross: 0.5 },
    { day: 9, indiaNet: 0.51, indiaGross: 0.6 },
    { day: 10, indiaNet: 0.48, indiaGross: 0.57 },
    { day: 11, indiaNet: 0.18, indiaGross: 0.21 },
  ]),
  fillDaily("paw-patrol-dino", "hungama", [
    { day: 1, indiaNet: 0.38, indiaGross: 0.45 },
    { day: 2, indiaNet: 0.84, indiaGross: 0.99 },
    { day: 3, indiaNet: 0.83, indiaGross: 0.98 },
    { day: 4, indiaNet: 0.22, indiaGross: 0.26 },
    { day: 5, indiaNet: 0.19, indiaGross: 0.22 },
    { day: 6, indiaNet: 0.16, indiaGross: 0.19 },
    { day: 7, indiaNet: 0.14, indiaGross: 0.17 },
    { day: 8, indiaNet: 0.18, indiaGross: 0.21 },
    { day: 9, indiaNet: 0.22, indiaGross: 0.26 },
    { day: 10, indiaNet: 0.2, indiaGross: 0.24 },
    { day: 11, indiaNet: 0.08, indiaGross: 0.09 },
  ]),
  fillDaily("hanuman-ansh", "hungama", [
    { day: 1, indiaNet: 0.1, indiaGross: 0.12 },
    { day: 2, indiaNet: 0.28, indiaGross: 0.33 },
    { day: 3, indiaNet: 0.26, indiaGross: 0.31 },
    { day: 7, indiaNet: 0.43, indiaGross: 0.51 },
    { day: 14, indiaNet: 1.85, indiaGross: 2.18 },
    { day: 21, indiaNet: 4.1, indiaGross: 4.84 },
    { day: 24, indiaNet: 1.2, indiaGross: 1.42, note: "Long-tail devotional; Hungama lifetime ~₹29.3 Cr nett." },
  ]),
  lifetime("hanuman-ansh", "hungama", 24, { worldwide: 38.09, indiaGross: 34.57, indiaNet: 29.3, overseas: 3.52 }, "Hungama lifetime ~₹29.3 Cr India nett. Sampled daily points are not a full cume."),
  fillDaily("spider-man-bnd", "hungama", [
    { day: 1, indiaNet: 61.0, indiaGross: 72.0, overseas: 0, worldwide: 72.0, note: "India figures. Global Fox/Sony numbers are tracked separately." },
    { day: 2, indiaNet: 98.4, indiaGross: 116.1 },
    { day: 3, indiaNet: 98.2, indiaGross: 115.9 },
    { day: 4, indiaNet: 28.5, indiaGross: 33.63 },
    { day: 5, indiaNet: 22.1, indiaGross: 26.08 },
    { day: 6, indiaNet: 16.4, indiaGross: 19.35 },
    { day: 7, indiaNet: 10.97, indiaGross: 12.94 },
    { day: 8, indiaNet: 8.2, indiaGross: 9.68 },
    { day: 9, indiaNet: 14.6, indiaGross: 17.23 },
    { day: 10, indiaNet: 15.1, indiaGross: 17.82 },
    { day: 14, indiaNet: 6.4, indiaGross: 7.55 },
    { day: 21, indiaNet: 4.8, indiaGross: 5.66 },
    { day: 28, indiaNet: 2.6, indiaGross: 3.07 },
    { day: 32, indiaNet: 0.95, indiaGross: 1.12 },
    { day: 33, indiaNet: 0.72, indiaGross: 0.85 },
  ]),
  lifetime("spider-man-bnd", "sacnilk", 33, { worldwide: 590.27, indiaGross: 590.27, indiaNet: 494.0, overseas: 0 }, "Sacnilk India gross ~₹590 Cr; net ~₹494 Cr. Overseas not in the India table."),

  fillDaily("dhamaal-4", "hungama", [
    { day: 1, indiaNet: 13.72, indiaGross: 16.19 },
    { day: 2, indiaNet: 24.8, indiaGross: 29.26 },
    { day: 3, indiaNet: 25.83, indiaGross: 30.48 },
    { day: 4, indiaNet: 9.4, indiaGross: 11.09 },
    { day: 5, indiaNet: 8.1, indiaGross: 9.56 },
    { day: 6, indiaNet: 7.05, indiaGross: 8.32 },
    { day: 7, indiaNet: 5.55, indiaGross: 6.55 },
    { day: 10, indiaNet: 8.2, indiaGross: 9.68 },
    { day: 14, indiaNet: 4.6, indiaGross: 5.43 },
    { day: 21, indiaNet: 3.1, indiaGross: 3.66 },
    { day: 28, indiaNet: 1.8, indiaGross: 2.12 },
    { day: 42, indiaNet: 0.4, indiaGross: 0.47 },
    { day: 52, indiaNet: 0.12, indiaGross: 0.14 },
  ]),
  lifetime("dhamaal-4", "wikipedia", 52, { worldwide: 238.55, indiaGross: 193.0, indiaNet: 163.77, overseas: 45.55 }, "Wikipedia worldwide ₹238.55 Cr."),

  fillDaily("the-odyssey", "hungama", [
    { day: 1, indiaNet: 16.08, indiaGross: 18.97 },
    { day: 2, indiaNet: 20.4, indiaGross: 24.07 },
    { day: 3, indiaNet: 20.37, indiaGross: 24.04 },
    { day: 4, indiaNet: 8.9, indiaGross: 10.5 },
    { day: 5, indiaNet: 7.6, indiaGross: 8.97 },
    { day: 6, indiaNet: 6.4, indiaGross: 7.55 },
    { day: 7, indiaNet: 5.9, indiaGross: 6.96 },
    { day: 14, indiaNet: 14.2, indiaGross: 16.76 },
    { day: 21, indiaNet: 9.8, indiaGross: 11.56 },
    { day: 28, indiaNet: 5.4, indiaGross: 6.37 },
    { day: 35, indiaNet: 2.1, indiaGross: 2.48 },
    { day: 45, indiaNet: 0.55, indiaGross: 0.65 },
  ]),
  lifetime("the-odyssey", "hungama", 45, { worldwide: 153.0, indiaGross: 138.88, indiaNet: 117.7, overseas: 14.12 }, "Hungama India run through Day 45. Worldwide ~₹153 Cr."),

  lifetime("dhurandhar", "hungama", 120, { worldwide: 1852.44, indiaGross: 1376.51, indiaNet: 1108.09, overseas: 475.93 }, "Hungama lifetime. Opening day nett published as ₹90 Cr vs Sacnilk ₹102.55 Cr."),
  lifetime("dhurandhar", "sacnilk", 120, { worldwide: 1852.44, indiaGross: 1375.39, indiaNet: 1149.3, overseas: 477.05 }, "Sacnilk India net ₹1,149.3 Cr — ~₹41 Cr above Hungama."),
  lifetime("dhurandhar", "wikipedia", 120, { worldwide: 1852.44, indiaGross: 1376.51, indiaNet: 1108.09, overseas: 475.93 }, "Compiled worldwide ₹1,852.44 Cr."),
  lifetime("dhurandhar", "boi", 90, { worldwide: 1820, indiaGross: 1350, indiaNet: 1095, overseas: 470 }, "Box Office India conservative nett."),

  lifetime("border-2", "hungama", 80, { worldwide: 464.5, indiaGross: 379, indiaNet: 321.2, overseas: 85.5 }, "Hungama / Wikipedia worldwide ₹464.50 Cr. Variety H1 India ₹379 Cr."),
  lifetime("border-2", "wikipedia", 80, { worldwide: 464.5, indiaGross: 379, indiaNet: 321, overseas: 85.5 }, "Wikipedia worldwide."),

  lifetime("peddi", "wikipedia", 70, { worldwide: 365, indiaGross: 300, indiaNet: 255, overseas: 65 }, "Published range ₹330–400 Cr. IBO logs the midpoint and flags the spread."),
  lifetime("peddi", "express", 70, { worldwide: 330, indiaGross: 280, indiaNet: 238, overseas: 50 }, "Lower band (Deccan Herald / Cinema Express)."),
  lifetime("peddi", "producer", 70, { worldwide: 400, indiaGross: 330, indiaNet: 280, overseas: 70 }, "Upper band (Economic Times / studio-adjacent)."),

  lifetime("jana-nayagan", "wikipedia", 60, { worldwide: 322.5, indiaGross: 280, indiaNet: 238, overseas: 42.5 }, "Range ₹320–325 Cr. OTT on ZEE5 from 21 Aug."),
  lifetime("karuppu", "wikipedia", 70, { worldwide: 312.5, indiaGross: 270, indiaNet: 229, overseas: 42.5 }, "Range ₹310–315 Cr."),
  lifetime("msvpg", "wikipedia", 70, { worldwide: 305, indiaGross: 255, indiaNet: 216, overseas: 50 }, "Range ₹300–310 Cr. Variety H1 India ₹255 Cr."),
  lifetime("bhooth-bangla", "wikipedia", 70, { worldwide: 247.28, indiaGross: 210, indiaNet: 178, overseas: 37.28 }, "Wikipedia worldwide ₹247.28 Cr."),
  lifetime("drishyam-3", "wikipedia", 80, { worldwide: 242, indiaGross: 205, indiaNet: 174, overseas: 37 }, "Wikipedia worldwide ₹242 Cr."),
  lifetime("vaazha-ii", "wikipedia", 80, { worldwide: 234.5, indiaGross: 210, indiaNet: 178, overseas: 24.5 }, "Range ₹234–235 Cr."),
  lifetime("welcome-jungle", "hungama", 66, { worldwide: 168, indiaGross: 154.3, indiaNet: 130.8, overseas: 13.7 }, "Hungama India nett ~₹130.8 Cr."),
  lifetime("cocktail-2", "hungama", 73, { worldwide: 118, indiaGross: 108.7, indiaNet: 92.09, overseas: 9.3 }, "Hungama India nett ₹92.09 Cr. Verdict: Average."),
  lifetime("alpha", "hungama", 59, { worldwide: 78, indiaGross: 68.1, indiaNet: 57.72, overseas: 9.9 }, "Hungama India nett ₹57.72 Cr. Verdict: Flop."),
];

export const TERRITORIES: TerritorySplit[] = [
  { movieId: "toxic", reportDate: "2026-08-26", territory: "Hindi", indiaNet: 55.0 },
  { movieId: "toxic", reportDate: "2026-08-26", territory: "Kannada", indiaNet: 23.3 },
  { movieId: "toxic", reportDate: "2026-08-26", territory: "Telugu", indiaNet: 16.0 },
  { movieId: "toxic", reportDate: "2026-08-26", territory: "Tamil", indiaNet: 5.5 },
  { movieId: "toxic", reportDate: "2026-08-26", territory: "Malayalam", indiaNet: 1.3 },
];

export function dateForDay(releaseDate: string, dayNumber: number): string {
  return addDays(releaseDate, dayNumber - 1);
}

export const SEEDED_HEADLINES: { sourceId: string; title: string; url: string; publishedAt: string; summary: string }[] = [
  {
    sourceId: "etimes",
    title: "'Vishwanath And Sons' Box Office: Day 17 nets Rs 2.55 crore",
    url: "https://timesofindia.indiatimes.com/entertainment/tamil/movies/box-office/vishwanath-and-sons-box-office-collections-day-17-suriya-and-mamitha-baiju-film-earns-rs-2-55-crore-1-9-dip-from-saturday/articleshow/133639335.cms",
    publishedAt: "2026-08-31T06:41:58+05:30",
    summary: "Suriya film earns ₹2.55 crore net with a 1.9% dip from Saturday as the third-week hold continues.",
  },
  {
    sourceId: "etimes",
    title: "'Hi' Box Office Day 3: Film nets ₹5.23cr in India",
    url: "https://timesofindia.indiatimes.com/entertainment/tamil/movies/box-office/hi-box-office-collections-day-3-nayanthara-kavin-starrer-crosses-rs-5-crore-sunday-occupancy-rises-to-47/articleshow/133639177.cms",
    publishedAt: "2026-08-31T06:15:08+05:30",
    summary: "Nayanthara–Kavin starrer crosses ₹5 crore India net; Sunday occupancy rises to 47%.",
  },
  {
    sourceId: "etimes",
    title: "Yash’s mother hits back at ‘Who was Yash before KGF?’",
    url: "https://timesofindia.indiatimes.com/entertainment/kannada/movies/news/toxic-star-yashs-mother-responds-to-questions-over-his-pre-kgf-stardom-he-was-giving-massive-hits/articleshow/133640854.cms",
    publishedAt: "2026-08-31T09:17:53+05:30",
    summary: "Family pushback as Toxic's weekday drop keeps the opening under a microscope.",
  },
  {
    sourceId: "express",
    title: "Toxic Box Office Collection Day 2: Yash film earns Rs 190 crore globally",
    url: "https://indianexpress.com/article/entertainment/regional/toxic-box-office-collection-day-2-worldwide-total-live-updates-yash-film-earns-rs-190-cr-10852410/",
    publishedAt: "2026-08-28T11:45:00+05:30",
    summary: "Indian Express live blog citing Sacnilk: Day 1 ₹101.1 Cr net, Day 2 ₹36.4 Cr net, WW ~₹190 Cr.",
  },
  {
    sourceId: "koimoi",
    title: "Toxic day-wise: ₹165.95 crore India net in 3 days",
    url: "https://www.koimoi.com/box-office/daily-breakdown/toxic-day-wise-box-office-collection/",
    publishedAt: "2026-08-29T12:00:00+05:30",
    summary: "Koimoi day-wise: 101.1 / 37.65 / 27.2. Worldwide ₹222.83 Cr through Day 3.",
  },
  {
    sourceId: "pinkvilla",
    title: "Toxic in a freefall: ₹178 Cr India gross in 3 days",
    url: "https://www.pinkvilla.com/entertainment/box-office/toxic-box-office-collections-yash-starrer-in-a-freefall-mode-earns-rs-178-cr-in-3-days-in-india-1405151",
    publishedAt: "2026-08-29T12:32:00+05:30",
    summary: "Pinkvilla India gross: Wed 111.75, Thu 38.50, Fri 27.75. Five-day extended weekend eyed at ~₹225 Cr.",
  },
  {
    sourceId: "wikipedia",
    title: "List of Indian films of 2026 — worldwide ranking",
    url: "https://en.wikipedia.org/wiki/List_of_Indian_films_of_2026",
    publishedAt: "2026-08-31T03:08:46+00:00",
    summary: "Dhurandhar: The Revenge ₹1,852.44 Cr still leads. Toxic enters the compiled table as currently showing.",
  },
];

export const SEEDED_REPORT = {
  reportDate: "2026-08-31",
  headline: "Toxic opens like a giant and holds like an argument",
  lede: "Monday 31 August. Six days after Yash's pan-India opening, the desk's job is not to pick a number. It is to publish the spread — because Sacnilk, Hungama and Pinkvilla are not describing the same film.",
  origin: "desk",
  body: `The Indian box office still has no official auditor. That is not a footnote. It is the product.

## The board, this Monday

**Toxic** remains the only new giant in theatres. Indian Box Office consensus through Day 6 is about **₹216 Cr India net** and **₹289 Cr worldwide**. That is a genuine big opening — and a genuine problem. Day 2 dropped 63% on Sacnilk. Saturday did not save it. Monday will be thin.

The more important number is the **disagreement**. Bollywood Hungama's Hindi-weighted Day-1 nett of ₹50.31 Cr is roughly half of Sacnilk/Koimoi's all-India ₹101.10 Cr. Pinkvilla's three-day India gross (₹178 Cr) sits ~9% below Koimoi (₹195.83 Cr). Wikipedia's compiled worldwide (₹254.75 Cr) already trails live trade. Anyone publishing a single "Toxic collection" without a source is inventing a fact.

**Awarapan 2** is the grown-up in the room. Seventeen days in, consensus India net is past **₹150 Cr** on a ₹45 Cr budget. Emraan Hashmi's sequel did the unfashionable thing: it grew on Saturday, entered ₹100 Cr on 19 August, and is still crawling forward. Hungama lifetime (~₹143.7 Cr nett) is a touch below Koimoi (~₹154 Cr). The spread is honest, not a war.

**Vishwanath And Sons** is the other split-screen. Sacnilk has the Suriya family drama around **₹116 Cr India net / ₹198 Cr WW** through Day 17. The producer has been printing **₹240–247 Cr worldwide**. That is a ₹50 Cr gap. We log both. We do not average a press release into a tracker.

**Irumudi** (Ravi Teja, 21 August) has already done the thing Toxic has not: hold. Nizam over-indexed, share crossed ₹100 Cr around Day 10, worldwide is in the mid-₹160s. This is the quiet hit of the fortnight.

**Hi** (Nayanthara, 28 August) is a small Tamil climb — ₹5.23 Cr India net in three days, Sunday occupancy 47%. Not a storm. A pulse.

Hollywood leftover: **Spider-Man: Brand New Day** is still the year's biggest English grosser in India (~₹494 Cr nett). **Insidious: Out of The Further** is a multiplex drip. **PAW Patrol** is matinees.

## The year, compressed

Dhurandhar: The Revenge (₹1,852 Cr WW) is not a film. It is a climate. Ormax had it at ~20% of India's H1 box office. Border 2, Peddi, Jana Nayagan, Karuppu and Mana Shankara Vara Prasad Garu fill out the 300-crore shelf. Peddi is still published as a range (₹330–400 Cr). That, again, is the point of this desk.

## What the bot is for

The IBO Desk does not cheer openings. It reads drop-offs, budget recovery, language mix and source conflict. Ask it why Hungama and Sacnilk cannot agree on Toxic. The answer is in the methodology, not in a press note.

Figures in crore. India net is the trade's working unit; worldwide is gross. Consensus is a weighted median, not a vibe.`,
};
