/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as NowRouteImport } from './routes/now'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WiresRouteImport } from './routes/wires'
import { Route as ApiDeskFileRouteImport } from './routes/api/desk-file'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as MoviesSlugRouteImport } from './routes/movies.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WiresRoute = WiresRouteImport.update({
  id: '/wires',
  path: '/wires',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskFileRoute = ApiDeskFileRouteImport.update({
  id: '/api/desk-file',
  path: '/api/desk-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoviesRoute,
} as any)
const MoviesSlugRoute = MoviesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MoviesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/download': typeof DownloadRoute
  '/movies': typeof MoviesRouteWithChildren
  '/now': typeof NowRoute
  '/rankings': typeof RankingsRoute
  '/report': typeof ReportRoute
  '/sources': typeof SourcesRoute
  '/wires': typeof WiresRoute
  '/api/desk-file': typeof ApiDeskFileRoute
  '/api/ingest': typeof ApiIngestRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/download': typeof DownloadRoute
  '/now': typeof NowRoute
  '/rankings': typeof RankingsRoute
  '/report': typeof ReportRoute
  '/sources': typeof SourcesRoute
  '/wires': typeof WiresRoute
  '/api/desk-file': typeof ApiDeskFileRoute
  '/api/ingest': typeof ApiIngestRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/movies': typeof MoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/download': typeof DownloadRoute
  '/movies': typeof MoviesRouteWithChildren
  '/now': typeof NowRoute
  '/rankings': typeof RankingsRoute
  '/report': typeof ReportRoute
  '/sources': typeof SourcesRoute
  '/wires': typeof WiresRoute
  '/api/desk-file': typeof ApiDeskFileRoute
  '/api/ingest': typeof ApiIngestRoute
  '/movies/$slug': typeof MoviesSlugRoute
  '/movies/': typeof MoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/download'
    | '/movies'
    | '/now'
    | '/rankings'
    | '/report'
    | '/sources'
    | '/wires'
    | '/api/desk-file'
    | '/api/ingest'
    | '/movies/$slug'
    | '/movies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/download'
    | '/now'
    | '/rankings'
    | '/report'
    | '/sources'
    | '/wires'
    | '/api/desk-file'
    | '/api/ingest'
    | '/movies/$slug'
    | '/movies'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/download'
    | '/movies'
    | '/now'
    | '/rankings'
    | '/report'
    | '/sources'
    | '/wires'
    | '/api/desk-file'
    | '/api/ingest'
    | '/movies/$slug'
    | '/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  DownloadRoute: typeof DownloadRoute
  MoviesRoute: typeof MoviesRouteWithChildren
  NowRoute: typeof NowRoute
  RankingsRoute: typeof RankingsRoute
  ReportRoute: typeof ReportRoute
  SourcesRoute: typeof SourcesRoute
  WiresRoute: typeof WiresRoute
  ApiDeskFileRoute: typeof ApiDeskFileRoute
  ApiIngestRoute: typeof ApiIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wires': {
      id: '/wires'
      path: '/wires'
      fullPath: '/wires'
      preLoaderRoute: typeof WiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-file': {
      id: '/api/desk-file'
      path: '/api/desk-file'
      fullPath: '/api/desk-file'
      preLoaderRoute: typeof ApiDeskFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/movies/$slug': {
      id: '/movies/$slug'
      path: '/$slug'
      fullPath: '/movies/$slug'
      preLoaderRoute: typeof MoviesSlugRouteImport
      parentRoute: typeof MoviesRoute
    }
  }
}

interface MoviesRouteChildren {
  MoviesSlugRoute: typeof MoviesSlugRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesSlugRoute: MoviesSlugRoute,
  MoviesIndexRoute: MoviesIndexRoute,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  DownloadRoute: DownloadRoute,
  MoviesRoute: MoviesRouteWithChildren,
  NowRoute: NowRoute,
  RankingsRoute: RankingsRoute,
  ReportRoute: ReportRoute,
  SourcesRoute: SourcesRoute,
  WiresRoute: WiresRoute,
  ApiDeskFileRoute: ApiDeskFileRoute,
  ApiIngestRoute: ApiIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
